### ISSUE TITLE
DOCKERize modules

### ISSUE THREAD

**Issue by cbadenes** [oeg-upm/epnoi#77]
- Docker-Compose for the base (elasticsearch, cassandra, neo4j, api, ftp, harvester and rabbitMQ
- Docker-Image for each module such as API, Harvester, LDA-Modeler, W2V-Modeler, Topic-Comparator and Learner
- Docker-Compose for the learner (Cassandra, Virtuoso and Learner-module)

**Comment by cbadenes** [comment]
According to this: https://spring.io/guides/gs/spring-boot-docker/

**Comment by cbadenes** [comment]
- Created docker-compose for Neo4j, Cassandra, Elasticsearch, RabbitMQ and Rest-API:
  https://hub.docker.com/u/librairy/dashboard/

**Comment by cbadenes** [comment]
``` yml
column-db:
  container_name: column-db
  image: librairy/column-db:1.0
  restart: always
  expose:
    - "9042"
    - "9160"
  ports:
    - "5010:8080"
    - "5011:9042"
    - "5012:9160"
document-db:
  container_name: document-db
  image: librairy/document-db:1.0
  restart: always
  expose:
    - "9200"
    - "9300"
  ports:
    - "5020:9200"
    - "5021:9300"
graph-db:
  container_name: graph-db
  image: librairy/graph-db:1.0
  restart: always
  expose:
    - "7474"
  ports:
    - "5030:7474"
event-bus:
  container_name: event-bus
  image: librairy/event-bus:1.0
  restart: always
  expose:
    - "15672"
    - "5672"
  ports:
    - "5040:15672"
    - "5041:5672"
explorer:
  container_name: explorer
  image: librairy/explorer:latest
  restart: always
  expose:
    - "8080"
  ports:
    - "8080:8080"
  links:
    - column-db
    - document-db
    - graph-db
    - event-bus
ftp:
  container_name: ftp
  image: librairy/ftp:1.0
  restart: always
  ports:
    - "5051:21"
  volumes:
    - ./data:/home/ftpusers/librairy
harvester:
  container_name: harvester
  image: librairy/harvester
  restart: always
  volumes:
    - ./data:/librairy/files/uploaded
  links:
      - column-db
      - document-db
      - graph-db
      - event-bus
modelerLDA:
  container_name: modelerLDA
  image: librairy/modeler-lda:0.2
  restart: always
  links:
      - column-db
      - document-db
      - graph-db
      - event-bus
modelerW2V:
  container_name: modelerW2V
  image: librairy/modeler-w2v:0.2
  restart: always
  links:
      - column-db
      - document-db
      - graph-db
      - event-bus
comparatorCOS:
  container_name: comparatorCOS
  image: librairy/modeler-cos:0.2
  restart: always
  links:
      - column-db
      - document-db
      - graph-db
      - event-bus
comparatorJSD:
  container_name: comparatorJSD
  image: librairy/modeler-jsd:0.2
  restart: always
  links:
      - column-db
      - document-db
      - graph-db
      - event-bus
```
